Storage Unit/StorageUnit/Controllers/StorageItemsController.cs
using StorageUnit.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StorageUnit.Controllers
{
    public class StorageItemsController : Controller
    {
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        
        //Метод който използваме за проверка на уникалността на Code
        public JsonResult IsCodeExist(int code)
        {
            var db = new ApplicationDbContext();
            var validateCode = db.StorageItems.FirstOrDefault
                                 (x => x.Code == code);
            if (validateCode != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        
        [HttpPost]
        public ActionResult Add (AddItemsViewModel addModel)
        {
           
               
                var db = new ApplicationDbContext();
                var addItems = new AddItemsViewModel
                {
                    ItemName = addModel.ItemName,
                    Description = addModel.Description,                   
                    Bought = addModel.Bought,
                    Selling = addModel.Selling,
                    Quantity = addModel.Quantity,
                    Type = addModel.Type,
                    Code = addModel.Code
                };
                db.StorageItems.Add(addItems);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");

            
        }       
    }

}

Storage Unit/StorageUnit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Storage", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                    <li>@Html.ActionLink("Add item", "Add", "StorageItems")</li>}                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Storage Unit</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>